version: "3"
services:
    ark-invest-api-rust:
        image: ghcr.io/nexveridian/ark-invest-api-rust:latest
        container_name: ark-invest-api-rust
        restart: unless-stopped
        volumes:
            - ./data:/ark-invest-api-rust/data
        ports:
            - "3000:3000"

volumes:
    data:
