version: "3"
services:
    ark-invest-api-rust:
        image: ark-invest-api-rust
        build:
            context: .
            args:
                DOCKER_BUILDKIT: 1
        container_name: ark-invest-api-rust
        restart: unless-stopped
        volumes:
            - ./data:/ark-invest-api-rust/data
        ports:
            - "3000:3000"

volumes:
    data:
